name: "Protolint Action"
description: "A tool to enforce Protocol Buffer style and conventions"
author: "Steven Silvestri"

branding:
  icon: "code"
  color: "black"

inputs:
  args:
    description: "protolint arguments"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - protolint
    - lint
    - ${{ inputs.args }}
